# Site settings
title: Stefano Meschiari
email: stefano.meschiari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Stefano Meschiari's personal website.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.stefanom.io"
twitter_username: StefanoWithAnF
github_username:  stefano-meschiari

# Build settings
markdown: kramdown
mathjax: true
exclude:
  - public/node_modules

excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"

# Compose settings
jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
      author: Stefano Meschiari
    posts:
      description:
      image:
      category:
      tags:
      author: Stefano Meschiari
      published: false
      sitemap: false

plugins:
  - jekyll-spaceship
  - jekyll-paginate